services:
  - type: web
    name: ipl-platform-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ipl-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: ipl-db
    plan: free
